# Generated by Django 4.2.16 on 2024-11-25 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vocab_mode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField()),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('accuracy_score', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='TestResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('sentence_meaning', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='test_mode.testresult')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab_mode.word')),
            ],
        ),
    ]
