# Generated by Django 4.2.16 on 2024-11-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_mode", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testresult",
            name="frequency_score",
        ),
    ]
