# Generated by Django 4.2.16 on 2024-11-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vocab_mode", "0002_remove_word_basic_example_and_more"),
        ("test_mode", "0002_remove_testresult_frequency_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="accuracy_score",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="TestResultDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField()),
                ("sentence_meaning", models.TextField()),
                ("is_correct", models.BooleanField()),
                (
                    "test_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="test_mode.testresult",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vocab_mode.word",
                    ),
                ),
            ],
        ),
    ]
