version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_DB=engdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    ports:
      - "5433:5432"

volumes:
  postgres_data:
