# Generated by Django 4.2.16 on 2024-11-25 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vocab_mode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('sentence_meaning', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab_mode.word')),
            ],
        ),
        migrations.CreateModel(
            name='LearningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_category', models.IntegerField()),
                ('learning_date', models.DateTimeField()),
                ('pronunciation_score', models.IntegerField()),
                ('accuracy_score', models.IntegerField()),
                ('frequency_score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab_mode.word')),
            ],
        ),
    ]
