# Generated by Django 4.2.16 on 2024-11-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vocab_mode", "0002_alter_word_audio_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="PronunciationPractice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vocab_mode.word",
                    ),
                ),
            ],
        ),
    ]
