# Generated by Django 4.2.16 on 2024-11-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pron_practice", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PronunciationPractice",
        ),
    ]
