# Generated by Django 4.2.16 on 2024-11-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, '1학년'), (2, '2학년'), (3, '3학년'), (4, '4학년'), (5, '5학년'), (6, '6학년')], null=True, verbose_name='학년'),
        ),
    ]
