# Generated by Django 4.2.16 on 2024-11-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_grade_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='unique_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='학생 코드'),
        ),
    ]
