# Generated by Django 4.2.16 on 2024-11-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentinfo_birth_date_studentinfo_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='name',
            field=models.CharField(default='이름 없음', max_length=30, verbose_name='이름'),
        ),
    ]
