# Generated by Django 4.2.16 on 2024-11-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, '1학년'), (2, '2학년'), (3, '3학년'), (4, '4학년'), (5, '5학년'), (6, '6학년')], default=1, null=True, verbose_name='학년'),
        ),
    ]
