# Generated by Django 4.2.16 on 2024-11-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("meaning", models.TextField()),
                ("basic_example", models.TextField()),
                ("example_meaning", models.TextField()),
                ("category", models.IntegerField()),
            ],
        ),
    ]
