# Generated by Django 4.2.16 on 2024-11-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('meanings', models.JSONField(default=dict)),
                ('part_of_speech', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.IntegerField()),
                ('examples', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
