# Generated by Django 4.2.16 on 2024-11-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_mode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='basic_example',
        ),
        migrations.RemoveField(
            model_name='word',
            name='example_meaning',
        ),
        migrations.RemoveField(
            model_name='word',
            name='meaning',
        ),
        migrations.AddField(
            model_name='word',
            name='examples',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='word',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='meanings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
