# Generated by Django 4.2.16 on 2024-11-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_mode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/native/'),
        ),
    ]
