# Generated by Django 4.2.16 on 2024-11-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_mode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
