# Generated by Django 4.2.16 on 2024-11-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab_mode", "0002_word_audio_file_word_meaning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabularybook",
            name="json_file",
            field=models.FileField(
                blank=True, null=True, upload_to="../utils/combined_words.json"
            ),
        ),
    ]
