# Generated by Django 4.2.16 on 2024-11-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab_mode", "0004_alter_vocabularybook_json_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="audio_file",
        ),
        migrations.RemoveField(
            model_name="word",
            name="meaning",
        ),
        migrations.RemoveField(
            model_name="word",
            name="pronunciation_guide",
        ),
        migrations.AlterField(
            model_name="word",
            name="text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
