# Generated by Django 4.2.16 on 2024-11-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_mode', '0006_remove_vocabularybook_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='example_translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='meaning',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
