name: Notify Slack on Push
on: push
jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 전체 Git 히스토리를 가져오도록 설정

    - name: Send Slack notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
        FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r HEAD)
        BRANCH_NAME=${{ github.ref#refs/heads/ }}
        
        # Slack 메시지 포맷
        PAYLOAD=$(
          jq -n --arg author_name "$AUTHOR_NAME" \
                --arg branch_name "$BRANCH_NAME" \
                --arg files_changed "$FILES_CHANGED" \
                --arg commit_message "$COMMIT_MESSAGE" \
                '{
                  text: ":rocket: *New Push by [\($author_name)]*\n\n*Branch:* \($branch_name)\n\n*Files Changed:*\n```\($files_changed)```\n\n*Commit Message:*\n```\($commit_message)```"
                }'
        )
        
        curl -X POST -H "Content-type:application/json" --data "$PAYLOAD" "$SLACK_WEBHOOK_URL"
